### ISSUE TITLE
Party Frames Randomly Disappear in LFG Instances

### ISSUE THREAD

**Issue by jmgrimes** [ls-/oUF_LS#10]
During LFG groups (that I've observed), the party frames randomly disappear, especially during trash fights.  They seem to come back after boss kills, and then disappear after a few more trash fights.

**Comment by ls-** [comment]
Yeah, I'm aware of this issue, I've commented on WOWI about it.

Hopefully, I've finally fixed this issue by https://github.com/ls-/oUF_LS/commit/6fab1a5856ccc3e07896afe71a7434b32ba5a4aa commit. It happens because I'm trying to mimic default party frame behaviour, I mean switching between usual and compact party frames.

But I'm thinking about making user disable my party frames and switch to compact variation manually. Doing things in restricted environment isn't helping.

**Comment by jmgrimes** [comment]
Sorry, I should have included that I'm running the latest master branch checkout which includes this commit.  It seems better than before the commit, but wanted to make you aware that it was still happening occasionally.

I'll see about putting some logging statements in there to see if I can figure out what's triggering it exactly.

**Comment by ls-** [comment]
Damn, I'll just remove this thingy, cuz dealing with non-secure actions in combat isn't doing as good as I hoped. And as far as I remember that was a reason, why it didn't work well in arenas T_T

Performing things automatically is cool, but some things have to be done manually, I guess.

Thanks for your feedback, will close this issue later.

**Comment by jmgrimes** [comment]
I saw the update to this come across yesterday.  I'll give it a thorough test tonight and provide any feedback I can.  Thanks!

**Comment by ls-** [comment]
Well, as I said, I just removed auto toggling, I left the part that detects a type of party frames one is using and either disables my party frames or lets them be.

**Comment by ls-** [comment]
Fixed one more thingy with 6cbcf4682428e71b50bd44e1d4451e616f72ff42
I guess, I can close it now...
